// Picks the social share card (og:image) for a page.
//
// The cards themselves are generated by scripts/generate-og-cards.mjs into
// public/og/ — see that file for why they exist at all (short version: the
// old og:image was a 192x192 logo, below every platform's minimum for a
// large card, so every shared link rendered as a text-only row).
//
// Lives in src/lib rather than api/ because the /api routes already import
// from here (see api/news-article.js pulling in newsBlocks.js) and this is
// plain data with no runtime deps.

export const SITE_URL = 'https://socialdevtechnologies.com';

// Every id here must have a matching public/og/dept-<id>.jpg. Kept as an
// explicit allowlist rather than interpolating department_ids straight into
// a path: those values come from an LLM draft, and an unrecognized one
// would otherwise produce an og:image URL that 404s — which platforms treat
// as "no image at all", the exact failure this whole change fixes.
const DEPARTMENT_CARDS = new Set([
  'sales', 'marketing', 'operations', 'finance', 'hr',
  'legal', 'support', 'engineering', 'data', 'strategy',
]);

export const OG_CARD_WIDTH = 1200;
export const OG_CARD_HEIGHT = 630;

/**
 * Share card for a news article.
 *
 * Precedence: the article's own generated illustration, then a card themed
 * to its first recognized department, then the generic news card. The
 * department step is what keeps a week of articles from all sharing one
 * identical preview.
 *
 * Returns { url, isCard } — isCard false means the size is unknown, so the
 * caller should drop og:image:width/height rather than assert 1200x630.
 */
export function articleOgImage(article) {
  if (article?.image_url) return { url: article.image_url, isCard: false };

  const dept = (article?.department_ids || []).find((id) => DEPARTMENT_CARDS.has(id));
  if (dept) return { url: `${SITE_URL}/og/dept-${dept}.jpg`, isCard: true };

  return { url: `${SITE_URL}/og/news.jpg`, isCard: true };
}

/** Share card for a section index or a guide (no per-item art). */
export function sectionOgImage(section) {
  const file = ['news', 'guides', 'default'].includes(section) ? section : 'default';
  return { url: `${SITE_URL}/og/${file}.jpg`, isCard: true };
}

/**
 * Rewrites the og:image / twitter:image / og:image:* tags in the built
 * index.html shell. Every /api SSR route needs exactly this, and doing it
 * with four near-identical regexes per route is how the guide route ended
 * up still pointing at /logo.jpeg after the news route was fixed.
 */
export function applyOgImage(html, { url, isCard }, alt) {
  let out = html
    .replace(/(<meta property="og:image" content=")[^"]*(")/, `$1${url}$2`)
    .replace(/(<meta name="twitter:image" content=")[^"]*(")/, `$1${url}$2`);

  if (isCard) {
    if (alt) {
      out = out.replace(/(<meta property="og:image:alt" content=")[^"]*(")/, `$1${alt}$2`);
    }
    return out;
  }

  // Unknown dimensions: strip the width/height/alt the shell asserts rather
  // than leave a 1200x630 claim on an image that isn't.
  return out.replace(/\s*<meta property="og:image:(?:width|height|alt)" content="[^"]*" \/>/g, '');
}
