-- ============================================================================
-- Course guides: add the missing Python setup and install steps (2026-09-25) - Builder 2 guides
--
-- Every Python guide tells students to run `python <file>.py` within its first
-- few steps, but none of them says how to get Python or install the libraries
-- the code imports (only 23-25 even list them, and only in "What you need").
-- A student following the steps literally hits "command not found" or
-- ModuleNotFoundError before the first check can pass.
--
--   * Each Python guide (all but #4, the no-code Make.com one) gets a new first
--     step: check or install Python 3.10+, create a .venv, and install exactly
--     the libraries that guide imports, with Mac/Linux and Windows commands.
--     Using a venv also makes plain `python` work on every system, which is
--     what every later step already says.
--   * Builder 2 guides 13-22 have the AI assistant write requirements.txt; the
--     step after that prompt now starts with `pip install -r requirements.txt`.
--   * "What you need" now lists Python on every Python guide.
--
-- 36 guarded edits to course_content rows 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25.
-- Each edit checks the current value first (md5 for text, exact match for
-- structured values, absence for new keys, array length + neighbour for
-- inserted steps) and the whole migration aborts, changing nothing, on any
-- mismatch. Section 1 is checksummed so a copy/paste slip also aborts.
-- Backup of the touched rows: public.course_content_backup_20260925_setup_b2 (RLS on, anon and
-- authenticated revoked). Run as ONE transaction (SQL editor, apply_migration,
-- or psql -1); the temp table is ON COMMIT DROP, so a non-transactional run
-- fails before writing anything.
--
-- Rollback (touched rows only):
--   update public.course_content c set session = b.session,
--          troubleshooting = b.troubleshooting, resources = b.resources,
--          updated_at = b.updated_at
--     from public.course_content_backup_20260925_setup_b2 b where b.course_id = c.course_id;
-- ============================================================================

-- 1. The edits, in order. "final" is where each edit's value sits once every
--    later insert has shifted it; the post-check reads it there.
create temp table content_edits (
  ord int primary key, course_id int not null, col text not null check (col in ('session','troubleshooting','resources')),
  path text[] not null, final text[] not null, kind text not null check (kind in ('str','json','add','insert')),
  old_md5 text, old_json text, new_text text not null
) on commit drop;

insert into content_edits values
  (1, 13, 'session', '{builds,0,steps,2,verify}', '{builds,0,steps,3,verify}', 'str', 'c7fcd56406c9c6eb85fe2666c5855770', null,
    $n$First install everything requirements.txt lists: run `python -m pip install -r requirements.txt` (with your .venv active). Then: run search.py with a real topic — you should see 10 titles and URLs printed. If you get an auth error, double-check TAVILY_API_KEY is loaded via python-dotenv.$n$),
  (2, 14, 'session', '{builds,0,steps,2,verify}', '{builds,0,steps,3,verify}', 'str', 'af9508220957952e3dcd5f11e20623a2', null,
    $n$First install everything requirements.txt lists: run `python -m pip install -r requirements.txt` (with your .venv active). Then: run the script — it should print a list of your actually-stale open deals. If nothing prints, lower `days` temporarily to confirm the filter logic works, then set it back to 7.$n$),
  (3, 15, 'session', '{builds,1,steps,0,verify}', '{builds,1,steps,0,verify}', 'str', '9d1991f3b4cd3a4239b2d0226365000f', null,
    $n$First install everything requirements.txt lists: run `python -m pip install -r requirements.txt` (with your .venv active). Then: run generate_posts() on your real weekly notes — you should get back 5 posts, each clearly a different type, and each one should sound like something you'd actually write (not generic LinkedIn-speak). Run validate_posts() on the result and confirm the missing list is empty.$n$),
  (4, 16, 'session', '{builds,1,steps,0,verify}', '{builds,1,steps,0,verify}', 'str', '4f41e78007b456c452350fd035b93919', null,
    $n$First install everything requirements.txt lists: run `python -m pip install -r requirements.txt` (with your .venv active). Then: run ingest.py — it should print "Upserted N chunks" where N is roughly (total words across your docs) / ~460. Check the Pinecone console — your index should now show N vectors.$n$),
  (5, 17, 'session', '{builds,1,steps,0,verify}', '{builds,1,steps,0,verify}', 'str', 'b16d3ecf6550d2e34871a11e712445cf', null,
    $n$First install everything requirements.txt lists: run `python -m pip install -r requirements.txt` (with your .venv active). Then: run extract_invoice() on one of your sample PDFs and print the result — you should get back valid JSON matching the schema with realistic values. Run validate() on it and confirm needs_review is False for a complete invoice and True (with the right missing_fields) if you test on a deliberately incomplete one.$n$),
  (6, 18, 'session', '{builds,0,steps,2,verify}', '{builds,0,steps,3,verify}', 'str', '1590b9c8ac0e83637ea99a62cd639028', null,
    $n$First install everything requirements.txt lists: run `python -m pip install -r requirements.txt` (with your .venv active). Then: run get_homepage_text(), get_recent_news(), and get_job_titles() on one competitor from your watchlist. You should get back readable homepage text, a list of news snippets, and a list of job titles (if the careers page returns mostly empty, note it — that competitor likely uses a JS-rendered career page).$n$),
  (7, 19, 'session', '{builds,0,steps,2,verify}', '{builds,0,steps,3,verify}', 'str', '9e85c53c3e56cec8a903c7768e077c08', null,
    $n$First install everything requirements.txt lists: run `python -m pip install -r requirements.txt` (with your .venv active). Then: open a test PR (or push a commit to an existing one) in your test repo. Your Flask server's console should print the payload, confirming the webhook is received and the signature check passes.$n$),
  (8, 20, 'session', '{builds,1,steps,0,verify}', '{builds,1,steps,0,verify}', 'str', 'f41ec4e1fd35076073b1fabebebb66ea', null,
    $n$First install everything requirements.txt lists: run `python -m pip install -r requirements.txt` (with your .venv active). Then: run score_candidate() on one CV against your jd.txt. You should get back a JSON object with all the scoring fields filled in with sensible values, and the strengths/gaps should reference things actually in that CV (not generic statements).$n$),
  (9, 21, 'session', '{builds,0,steps,2,verify}', '{builds,0,steps,3,verify}', 'str', 'dd580beeedbf199f6d804a9cef2123f5', null,
    $n$First install everything requirements.txt lists: run `python -m pip install -r requirements.txt` (with your .venv active). Then: run it with your target keyword — you should see a search volume number and a list of 10 competing article titles/URLs. Note DataForSEO charges per call, so avoid running this in a loop during development.$n$),
  (10, 22, 'session', '{builds,0,steps,2,verify}', '{builds,0,steps,3,verify}', 'str', '266ac5a2e9c25e69d81a359b4964c970', null,
    $n$First install everything requirements.txt lists: run `python -m pip install -r requirements.txt` (with your .venv active). Then: run load_transactions() then clean_transactions() on your CSV and print df.head() and df["category"].unique() - categories should look consistent (no duplicates differing only by case/whitespace), and the row count should be lower if your CSV had duplicates.$n$),
  (11, 13, 'session', '{whatYouNeed,1}', '{whatYouNeed,1}', 'insert', '21d2e9b1557d64eecc95ad14adb9dd98', $o$4$o$,
    $n$"Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)"$n$),
  (12, 14, 'session', '{whatYouNeed,1}', '{whatYouNeed,1}', 'insert', '21d2e9b1557d64eecc95ad14adb9dd98', $o$5$o$,
    $n$"Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)"$n$),
  (13, 15, 'session', '{whatYouNeed,1}', '{whatYouNeed,1}', 'insert', '21d2e9b1557d64eecc95ad14adb9dd98', $o$4$o$,
    $n$"Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)"$n$),
  (14, 16, 'session', '{whatYouNeed,1}', '{whatYouNeed,1}', 'insert', '21d2e9b1557d64eecc95ad14adb9dd98', $o$4$o$,
    $n$"Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)"$n$),
  (15, 17, 'session', '{whatYouNeed,1}', '{whatYouNeed,1}', 'insert', '21d2e9b1557d64eecc95ad14adb9dd98', $o$5$o$,
    $n$"Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)"$n$),
  (16, 18, 'session', '{whatYouNeed,1}', '{whatYouNeed,1}', 'insert', '21d2e9b1557d64eecc95ad14adb9dd98', $o$4$o$,
    $n$"Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)"$n$),
  (17, 19, 'session', '{whatYouNeed,1}', '{whatYouNeed,1}', 'insert', '38bf9f960a0dc8722a12b2d33d619401', $o$4$o$,
    $n$"Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)"$n$),
  (18, 20, 'session', '{whatYouNeed,1}', '{whatYouNeed,1}', 'insert', '38bf9f960a0dc8722a12b2d33d619401', $o$4$o$,
    $n$"Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)"$n$),
  (19, 21, 'session', '{whatYouNeed,1}', '{whatYouNeed,1}', 'insert', '38bf9f960a0dc8722a12b2d33d619401', $o$4$o$,
    $n$"Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)"$n$),
  (20, 22, 'session', '{whatYouNeed,1}', '{whatYouNeed,1}', 'insert', '21d2e9b1557d64eecc95ad14adb9dd98', $o$4$o$,
    $n$"Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)"$n$),
  (21, 23, 'session', '{whatYouNeed,0}', '{whatYouNeed,0}', 'str', '3506f1ef1c15c83e87bdfdd4ecfefae5', null,
    $n$Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)$n$),
  (22, 24, 'session', '{whatYouNeed,0}', '{whatYouNeed,0}', 'str', '3506f1ef1c15c83e87bdfdd4ecfefae5', null,
    $n$Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)$n$),
  (23, 25, 'session', '{whatYouNeed,0}', '{whatYouNeed,0}', 'str', '3506f1ef1c15c83e87bdfdd4ecfefae5', null,
    $n$Python 3.10 or newer (free at python.org - the first step shows how to check and set it up)$n$),
  (24, 13, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$3$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the two libraries sdt_ai.py needs (the rest get installed from requirements.txt once your AI assistant writes it, a few steps from now).", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (25, 14, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$3$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the two libraries sdt_ai.py needs (the rest get installed from requirements.txt once your AI assistant writes it, a few steps from now).", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (26, 15, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$3$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the two libraries sdt_ai.py needs (the rest get installed from requirements.txt once your AI assistant writes it, a few steps from now).", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (27, 16, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$3$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the two libraries sdt_ai.py needs (the rest get installed from requirements.txt once your AI assistant writes it, a few steps from now).", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (28, 17, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$3$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the two libraries sdt_ai.py needs (the rest get installed from requirements.txt once your AI assistant writes it, a few steps from now).", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (29, 18, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$3$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the two libraries sdt_ai.py needs (the rest get installed from requirements.txt once your AI assistant writes it, a few steps from now).", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (30, 19, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$3$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the two libraries sdt_ai.py needs (the rest get installed from requirements.txt once your AI assistant writes it, a few steps from now).", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (31, 20, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$3$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the two libraries sdt_ai.py needs (the rest get installed from requirements.txt once your AI assistant writes it, a few steps from now).", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (32, 21, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$3$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the two libraries sdt_ai.py needs (the rest get installed from requirements.txt once your AI assistant writes it, a few steps from now).", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (33, 22, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$3$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the two libraries sdt_ai.py needs (the rest get installed from requirements.txt once your AI assistant writes it, a few steps from now).", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (34, 23, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$2$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the libraries this guide uses.", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv PyPDF2 python-docx\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv PyPDF2 python-docx\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (35, 24, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$2$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the libraries this guide uses.", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv pandas\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv pandas\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$),
  (36, 25, 'session', '{builds,0,steps,0}', '{builds,0,steps,0}', 'insert', 'dd1ae3148e8fa1364d7f595419e3a445', $o$2$o$,
    $n${"instruction": "Set up Python for this project (once, about 5 minutes). Check your version with `python3 --version` on Mac/Linux or `py --version` on Windows. If it is missing or older than 3.10, install the latest Python from python.org/downloads (on Windows, tick \"Add python.exe to PATH\" on the installer's first screen), then open a new terminal. Now make an empty folder for this project, open a terminal in it (in VS Code: File > Open Folder, then Terminal > New Terminal), and run the commands below for your system. They create a virtual environment - a private set of libraries for this project only - and install the libraries this guide uses.", "prompt": "# Mac / Linux\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pip install requests python-dotenv tavily-python\n\n# Windows (PowerShell)\npy -m venv .venv\n.venv\\Scripts\\Activate.ps1\npython -m pip install requests python-dotenv tavily-python\n\n# Windows says \"running scripts is disabled\"? Run this once, then the Activate line again:\n#   Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\n# Ubuntu/Debian says venv or ensurepip is not available? Run: sudo apt install python3-venv", "verify": "Your terminal prompt now starts with (.venv), and the install ended with \"Successfully installed\". Each time you open a new terminal for this project, run the activate line again first - while it is active, plain `python` works on every system, and that is the command every step below uses."}$n$);

-- 2. Self-check, pre-flight guards, backup, apply, post-check.
do $$
declare e record; cur jsonb; par jsonb; n int;
begin
  if (select md5(string_agg(h, '' order by h collate "C")) from (
        select md5(concat_ws(E'\x1f', ord::text, course_id::text, col, array_to_string(path, '.'),
                             array_to_string(final, '.'), kind, new_text)) as h
          from content_edits) s) <> 'cf799d72b7b62bcd053a569e763995d2' then
    raise exception 'Section 1 is not the reviewed copy - nothing was changed.';
  end if;
  if to_regclass('public.course_content_backup_20260925_setup_b2') is not null then
    raise exception 'public.course_content_backup_20260925_setup_b2 already exists - has this migration already run?';
  end if;
  create table public.course_content_backup_20260925_setup_b2 as
    select course_id, session, troubleshooting, resources, updated_at from public.course_content
     where course_id in (13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25);
  alter table public.course_content_backup_20260925_setup_b2 enable row level security;
  revoke all on public.course_content_backup_20260925_setup_b2 from anon, authenticated;

  for e in select * from content_edits order by ord loop
    n := array_length(e.path, 1);
    execute format('select %I #> $1, %I #> $2 from public.course_content where course_id = $3', e.col, e.col)
      into cur, par using e.path, e.path[1:n-1], e.course_id;
    if (e.kind = 'str' and md5(cur #>> '{}') is distinct from e.old_md5)
       or (e.kind = 'json' and cur is distinct from e.old_json::jsonb)
       or (e.kind = 'add' and (cur is not null or jsonb_typeof(par) is distinct from 'object'))
       or (e.kind = 'insert' and (jsonb_typeof(par) is distinct from 'array'
            or jsonb_array_length(par) <> e.old_json::int
            or md5(coalesce(cur ->> 'instruction', cur #>> '{}')) is distinct from e.old_md5)) then
      raise exception 'edit % (course % %.%) does not match the audited value - nothing was changed',
        e.ord, e.course_id, e.col, array_to_string(e.path, '.');
    end if;
    if e.kind = 'insert' then
      execute format('update public.course_content set %I = jsonb_insert(%I, $1, $2), updated_at = now() where course_id = $3', e.col, e.col)
        using e.path, e.new_text::jsonb, e.course_id;
    else
      execute format('update public.course_content set %I = jsonb_set(%I, $1, $2), updated_at = now() where course_id = $3', e.col, e.col)
        using e.path, case when e.kind = 'str' then to_jsonb(e.new_text) else e.new_text::jsonb end, e.course_id;
    end if;
  end loop;

  for e in select * from content_edits order by ord loop
    execute format('select %I #> $1 from public.course_content where course_id = $2', e.col)
      into cur using e.final, e.course_id;
    if cur is distinct from (case when e.kind = 'str' then to_jsonb(e.new_text) else e.new_text::jsonb end) then
      raise exception 'post-check: edit % (course %) did not land - rolling back', e.ord, e.course_id;
    end if;
  end loop;
  if exists (select 1 from public.course_content where updated_at = now() and course_id not in (13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)) then
    raise exception 'post-check: an untouched row changed - rolling back';
  end if;
end $$;
