-- ============================================================================
-- Course guides: inline the files/README steps students never get, and fix Builder 1 code bugs (2026-09-26)
--
-- Students only see the guide page; the repo's starter projects (README.md,
-- .env.example, sample files) are not handed out. Guides that pointed at them:
--   * #5 read an "included" sample_transcript.txt: now a step to create it.
--   * #12 had students open five "included" files in sample_data/: now a
--     make_samples.py step writes them (byte-identical to the starter files).
--   * #8 offered an "included" sample.txt: now suggests a web page URL.
--   * #6, #7, #8 said "copy .env.example": now say what to put in .env.
--   * #3 sent students to README.md for the Slack .env values and the
--     cron / Task Scheduler setup: both are now in the guide itself.
--   * #10 and #11 code comments/messages pointed at README sections.
--   * #6 deploy step assumed a requirements.txt nobody told students to make.
--   * #10 troubleshooting still promised a "free always-on host".
--
-- Code bugs (each file re-run against its own self-test, plus new checks):
--   * #2 app.py: an AIError (busy/rate-limited Gemini) became a 500, so the
--     sender got no reply at all. Now sends a fallback reply; new test.
--   * #3 slack_client.py fetched 24 DAYS of history (hours * SECONDS_PER_DAY).
--   * #3 summarizer.py cut the prompt with [:MAX_CHARACTERS], which kept the
--     oldest messages and dropped the newest - the ones the briefing is for.
--     Now trims the oldest lines, with an equal share per channel.
--   * #10 main.py reported every target as a "new product" on the first run,
--     and dropped a target that failed to scrape from the saved snapshot.
--   * #11 calendar_client.py sent local midnight with a "Z" (UTC) suffix, so
--     "today" was shifted by the UTC offset; main.py did not catch the
--     ValueError plan_day raises for a badly formatted reply.
--   * #2 deploy prompt never asked for the requirements.txt Railway needs.
--
-- 32 guarded edits to course_content rows 2, 3, 5, 6, 7, 8, 10, 11, 12.
-- Each edit checks the current value first (md5 for text, exact match for
-- structured values, absence for new keys, array length + neighbour for
-- inserted steps) and the whole migration aborts, changing nothing, on any
-- mismatch. Section 1 is checksummed so a copy/paste slip also aborts.
-- Long texts with small changes ship as "patch" hunks: each hunk must match
-- exactly once and the patched text must hash to the reviewed new_md5.
-- Backup of the touched rows: public.course_content_backup_20260926_b1_fixes (RLS on, anon and
-- authenticated revoked). Run as ONE transaction (SQL editor, apply_migration,
-- or psql -1); the temp table is ON COMMIT DROP, so a non-transactional run
-- fails before writing anything.
--
-- Rollback (touched rows only):
--   update public.course_content c set session = b.session,
--          troubleshooting = b.troubleshooting, resources = b.resources,
--          updated_at = b.updated_at
--     from public.course_content_backup_20260926_b1_fixes b where b.course_id = c.course_id;
-- ============================================================================

-- 1. The edits, in order. "final" is where each edit's value sits once every
--    later insert has shifted it; the post-check reads it there.
create temp table content_edits (
  ord int primary key, course_id int not null, col text not null check (col in ('session','troubleshooting','resources')),
  path text[] not null, final text[] not null, kind text not null check (kind in ('str','patch','json','add','insert')),
  old_md5 text, old_json text, new_text text not null, new_md5 text
) on commit drop;

insert into content_edits values
  (1, 5, 'session', '{builds,0,steps,2,verify}', '{builds,0,steps,3,verify}', 'str', '180c701e3865352c86d99530f2e2855d', null,
    $n$Run `python notes.py`. It reads the `sample_transcript.txt` you just saved, prints how many characters it got, and then checks that a missing file and a near-empty transcript both raise a clear error instead of crashing - you should see "Correctly raised an error" printed twice.$n$, null),
  (2, 5, 'session', '{builds,2,steps,1,verify}', '{builds,2,steps,1,verify}', 'str', '0672142bc0f50cda81a3a6196a4671c7', null,
    $n$Run `python main.py sample_transcript.txt` - the test transcript you saved in Build 1. Within a few seconds you should see structured Markdown printed to your console (Summary, Decisions, an Action Items table), followed by a line showing the timestamped file it saved inside `notes_output/`.$n$, null),
  (3, 5, 'session', '{builds,0,steps,2}', '{builds,0,steps,2}', 'insert', '08c549b2816a0e83414b099e243ed086', $o$3$o$,
    $n${"instruction": "Create a file called sample_transcript.txt and paste in the text below - a short, deliberately messy meeting transcript (someone joins late, and one task ends up with no owner) to test with. Swap in one of your own meetings once everything works.", "prompt": "Weekly Product Sync - Sept 1\n\nAttendees: Amaka, Tunde, Chidi, Priya (dialed in late)\n\nAmaka: ok let's get started, we're behind on the onboarding redesign.\nTunde: yeah the Figma files are done, dev just hasn't picked it up yet\nChidi: I can start on it Monday if nobody else is on it\nAmaka: sounds good, go ahead Chidi\n\nAmaka: also, we need to decide on the pricing page - do we keep the\nold three-tier layout or switch to the new single-price page marketing\nsent over?\nTunde: I vote we switch, the old one is confusing people, support tickets\nabout pricing are up like 30% this month\nChidi: agreed, let's switch\nAmaka: ok, decision made - we're moving to the single-price layout\n\nPriya joins late: sorry I'm late, what did I miss\n\nAmaka: quick recap - Chidi's starting the onboarding redesign Monday,\nand we're switching the pricing page to the single-price layout\n\nTunde: one more thing, someone needs to email the beta testers about\nthe pricing change before we ship it, don't want them blindsided\nAmaka: good call\nChidi: I don't think that's on me, I'm heads down on onboarding\nTunde: I can't this week either, I'm out Thursday and Friday\nAmaka: ...ok someone needs to own that, let's figure it out after the call\n\nAmaka: last thing - can we get the pricing switch live by end of month?\nTunde: should be doable, maybe the 28th\nAmaka: let's lock the 28th as the target then\n\nPriya: quick question, are we still doing the quarterly review next week?\nAmaka: yes, same time, I'll send the invite\n\nAmaka: ok that's everything, thanks all\n"}$n$, null),
  (4, 12, 'session', '{builds,0,steps,1,instruction}', '{builds,0,steps,1,instruction}', 'str', 'd7b9ad98fc6d20d9d6f9f49e5febd87c', null,
    $n$Create a file called make_samples.py, paste in the code below, and run `python make_samples.py`. It creates a sample_data/ folder with five short test documents - a business card blurb, an email signature, a job posting, a product review, and a real estate listing. Open them and skim them. Notice how differently each one is written; that's exactly the kind of messy, real-world text this project extracts from.$n$, null),
  (5, 12, 'session', '{builds,0,steps,1,prompt}', '{builds,0,steps,1,prompt}', 'add', null, null,
    $n$"\"\"\"\nCreates the sample_data/ folder this project reads from: five short test\ndocuments, each written in a very different style. Run it once:\n\n    python make_samples.py\n\nLater, drop your own .txt files into sample_data/ - main.py processes\nevery .txt file it finds there.\n\"\"\"\n\nimport os\n\nSAMPLES = {\n    \"business_card.txt\": \"\"\"\\\nSarah Okafor\nSenior Product Manager, Fintech Solutions Ltd.\n\nPhone: +234 803 555 0192\nEmail: sarah.okafor@fintechsolutions.ng\nLagos, Nigeria\n\"\"\",\n    \"email_signature.txt\": \"\"\"\\\nBest regards,\n\nDavid Chen\nAccount Executive | BrightPath Consulting\n\nMobile: (415) 555-2077\nEmail: david.chen@brightpathconsulting.com\nBook a meeting: calendly.com/davidchen\n\nThis email and any attachments are confidential and intended solely for\nthe addressee.\n\"\"\",\n    \"job_posting.txt\": \"\"\"\\\nWe're Hiring: Backend Engineer (Remote)\n\nTechNova Inc. is looking for a Backend Engineer to join our growing\nplatform team. You'll work on our payments API and internal tooling.\n\nSalary: $75,000 - $95,000 per year, depending on experience.\nApplication deadline: October 31, 2026.\n\nTo apply, send your resume and a short cover note to careers@technova.io.\nNo phone calls, please - we review every application by email.\n\"\"\",\n    \"product_review.txt\": \"\"\"\\\nProduct Review: The EcoBrew Coffee Maker\n\nThis coffee maker is made mostly from recycled materials and cuts\nbrewing time by almost half compared to our old machine. It has three\nbrew-strength settings and an auto-shutoff feature that has already\nsaved us from a couple of forgetful mornings.\n\nThe water tank could be a little bigger, and the instructions that came\nin the box were confusing, but overall this is a solid choice for anyone\nlooking to reduce their environmental footprint without sacrificing\ntheir morning routine.\n\"\"\",\n    \"real_estate_listing.txt\": \"\"\"\\\nFOR SALE: 3-Bedroom Duplex, Lekki Phase 1, Lagos\n\nPrice: NGN 85,000,000 (negotiable)\n\nSpacious 3-bedroom duplex with a boys' quarters, fitted kitchen, and\n24-hour power backup. Gated estate with 24/7 security.\n\nListed on: 2026-08-15\n\nContact the agent, Chidinma Eze, on 0807 123 4567 for a viewing.\nSerious inquiries only, please.\n\"\"\",\n}\n\nos.makedirs(\"sample_data\", exist_ok=True)\nfor name, text in SAMPLES.items():\n    with open(os.path.join(\"sample_data\", name), \"w\", encoding=\"utf-8\") as f:\n        f.write(text)\nprint(f\"Created sample_data/ with {len(SAMPLES)} files.\")\n"$n$, null),
  (6, 12, 'session', '{builds,0,steps,1,verify}', '{builds,0,steps,1,verify}', 'add', null, null,
    $n$"You should see \"Created sample_data/ with 5 files.\" and five .txt files inside the new sample_data/ folder."$n$, null),
  (7, 12, 'session', '{whatYouNeed,3}', '{whatYouNeed,3}', 'str', '336608bd89ccf6f1f411cd100f273b14', null,
    $n$The five sample documents the first build creates in sample_data/ (a business card blurb, an email signature, a job posting, a product review, and a real estate listing) - or your own .txt files later$n$, null),
  (8, 8, 'session', '{whatYouNeed,3}', '{whatYouNeed,3}', 'str', 'e4fa0cdc6f69d2d91ce11c9a2deaf1ce', null,
    $n$A PDF or Word document to test with (a contract, report, or article works well) - or just a web article's URL$n$, null),
  (9, 8, 'session', '{builds,2,steps,0,verify}', '{builds,2,steps,0,verify}', 'str', '71cbe1386c5cf8d523c31c1187b7191b', null,
    $n$Run `python main.py path/to/your/document.pdf` (a .txt or .docx file, or a web page's URL, work too - with nothing to hand, try `python main.py https://en.wikipedia.org/wiki/Artificial_intelligence`). You should see the character count, then KEY POINTS, ACTION ITEMS, and EXECUTIVE BRIEF sections printed in order.$n$, null),
  (10, 6, 'session', '{builds,0,steps,1,verify}', '{builds,0,steps,1,verify}', 'str', 'b92eaf7fa29153dbe29bab9e320fdc85', null,
    $n$Create a .env file next to it containing GEMINI_API_KEY=your_key_here (get a free one at https://aistudio.google.com/apikey), then run `python sdt_ai.py` - you should see "Your setup works. You are ready to build." printed after a short AI-generated greeting.$n$, null),
  (11, 7, 'session', '{builds,1,steps,0,verify}', '{builds,1,steps,0,verify}', 'str', '124f178a19e34f52d67f68b4bc7c69ca', null,
    $n$Create a .env file next to it containing GEMINI_API_KEY=your_key_here (get a free one at aistudio.google.com/apikey), then run `python sdt_ai.py` - you should see "The AI said: ..." and "Your setup works. You are ready to build."$n$, null),
  (12, 8, 'session', '{builds,1,steps,0,verify}', '{builds,1,steps,0,verify}', 'str', '124f178a19e34f52d67f68b4bc7c69ca', null,
    $n$Create a .env file next to it containing GEMINI_API_KEY=your_key_here (get a free one at aistudio.google.com/apikey), then run `python sdt_ai.py` - you should see "The AI said: ..." and "Your setup works. You are ready to build."$n$, null),
  (13, 3, 'session', '{builds,2,steps,0,prompt}', '{builds,2,steps,0,prompt}', 'patch', '33d7166b7d52c43981550baadc89609b', null,
    $n$[["\nOr skip the `schedule` package entirely and let your OS handle the timing -\nsee the README for the crontab (Mac/Linux) and Task Scheduler (Windows)\nequivalents. Both approaches call the same run_briefing() function; only\nwho presses the button (this file, or your OS) is different.\n\"\"\"\n", "\nOr skip the `schedule` package entirely and let your OS handle the timing -\nthe guide's last step shows the crontab (Mac/Linux) and Task Scheduler\n(Windows) setups. Both approaches call the same run_briefing() function; only\nwho presses the button (this file, or your OS) is different.\n\"\"\"\n"], ["        print(\n            \"Missing SLACK_BOT_TOKEN or SLACK_USER_ID.\\n\"\n            \"Copy .env.example to .env, uncomment those two lines, and fill \"\n            \"them in - see README.md for where to find each value.\"\n        )\n        return\n", "        print(\n            \"Missing SLACK_BOT_TOKEN or SLACK_USER_ID.\\n\"\n            \"Add both to your .env file: SLACK_BOT_TOKEN=xoxb-... (the Bot User \"\n            \"OAuth Token from Build 1) and SLACK_USER_ID=U... (your member ID).\"\n        )\n        return\n"], ["        # This only works while the process itself stays alive - if your\n        # laptop sleeps or you close the terminal, nothing runs. Cron /\n        # Task Scheduler (see README) survive both; this is the quick way\n        # to test the daily timing without setting either up first.\n        schedule.every().day.at(\"08:00\").do(run_briefing)\n        print(\"Scheduled for 08:00 daily. Leave this running... (Ctrl+C to stop)\")\n", "        # This only works while the process itself stays alive - if your\n        # laptop sleeps or you close the terminal, nothing runs. Cron /\n        # Task Scheduler (the guide's last step) survive both; this is\n        # the quick way to test the daily timing without setting either\n        # up first.\n        schedule.every().day.at(\"08:00\").do(run_briefing)\n        print(\"Scheduled for 08:00 daily. Leave this running... (Ctrl+C to stop)\")\n"]]$n$, '8fbe314d17152f9076eb40e3fddc936f'),
  (14, 3, 'session', '{builds,2,steps,0,verify}', '{builds,2,steps,0,verify}', 'str', '1a4ed36fb3b2fe24e8d970c72a28d27b', null,
    $n$Add two lines to the .env file you made in Build 2: SLACK_BOT_TOKEN=xoxb-... (the Bot User OAuth Token from Build 1) and SLACK_USER_ID=U... (your member ID). Then replace CHANNEL_IDS near the top of main.py with your real channel IDs (right-click a channel name > View channel details, scroll to the bottom), then run `python main.py`. Within about 20 seconds you should get a DM titled "Morning Briefing - <today's date>" with Top Priorities / FYI sections, and "Briefing sent!" in your console.$n$, null),
  (15, 3, 'session', '{builds,2,steps,1,instruction}', '{builds,2,steps,1,instruction}', 'str', '9e39a834b409dc43cdc91f5c8b96fd7b', null,
    $n$Now set it up to run every morning on its own. Either run `python main.py --schedule` and leave that process running (it uses the schedule package to fire at 08:00 daily), or - better, since it survives a reboot - use your OS's own scheduler: crontab on Mac/Linux, or Task Scheduler on Windows (both exact setups are below - replace /full/path/to/project with your project folder's real path, which `pwd` on Mac/Linux or `cd` on Windows prints).$n$, null),
  (16, 3, 'session', '{builds,2,steps,1,prompt}', '{builds,2,steps,1,prompt}', 'add', null, null,
    $n$"# Mac/Linux (cron): run `crontab -e`, add this one line, save and close.\n# It runs at 08:00 every day and writes whatever main.py prints to briefing.log.\n0 8 * * * cd /full/path/to/project && /full/path/to/project/.venv/bin/python main.py >> briefing.log 2>&1\n\n# On a Mac, cron cannot read folders inside Documents, Desktop or Downloads unless you give it\n# Full Disk Access (System Settings > Privacy & Security > Full Disk Access > add /usr/sbin/cron),\n# so either do that or keep the project somewhere else in your home folder.\n\n# Windows (Task Scheduler): Create Basic Task > Trigger: Daily, 8:00 AM >\n# Action: Start a program, then fill in:\n#   Program/script:  C:\\full\\path\\to\\project\\.venv\\Scripts\\python.exe\n#   Add arguments:   main.py\n#   Start in:        C:\\full\\path\\to\\project"$n$, null),
  (17, 10, 'session', '{builds,1,steps,0,prompt}', '{builds,1,steps,0,prompt}', 'patch', 'a60fa803b535e2fc952c2a4e8b0f429b', null,
    $n$[["    That last one is deliberately vague about WHY it disappeared --\n    delisted, or your selector stopped matching -- because this function\n    has no way to tell those apart. See the README's troubleshooting\n    section for how a human tells them apart.\n    \"\"\"\n    changes = []\n", "    That last one is deliberately vague about WHY it disappeared --\n    delisted, or your selector stopped matching -- because this function\n    has no way to tell those apart. A human can: open the product page in\n    a browser - if it is still listed, the selector broke (the site's\n    HTML changed), so update it in main.py's TARGETS.\n    \"\"\"\n    changes = []\n"], ["\n    # A snapshot compared against itself must never produce noise. This\n    # is exactly the bug the README's troubleshooting section warns\n    # about (\"getting an alert on every run even with no real change\")\n    # -- usually caused by comparing raw scraped text that has stray\n", "\n    # A snapshot compared against itself must never produce noise. This\n    # is exactly the bug the guide's troubleshooting section warns\n    # about (\"getting an alert on every run even with no real change\")\n    # -- usually caused by comparing raw scraped text that has stray\n"]]$n$, 'f6b01b0bf2e13b23d47cb529fe244f5f'),
  (18, 10, 'troubleshooting', '{3,fix}', '{3,fix}', 'str', '821f1c502cd1da22a2fe0ce0ccf5fcd5', null,
    $n$If it's running on your own laptop, the schedule pauses whenever your laptop sleeps. For real always-on monitoring, schedule it with cron or Task Scheduler on a machine that stays on, or deploy it to an always-on host such as Railway or Render (check their current plans - neither keeps a job running 24/7 for free).$n$, null),
  (19, 6, 'session', '{builds,2,steps,1,instruction}', '{builds,2,steps,1,instruction}', 'str', '3e1e0ad0a62349939745c6afce8c3cc6', null,
    $n$First create requirements.txt next to app.py with three lines - streamlit, requests, python-dotenv - so Streamlit Cloud knows which libraries to install. Then paste this prompt into your AI coding assistant of choice (Claude Code, Cursor, Gemini CLI, ChatGPT, etc.) to walk through deployment:$n$, null),
  (20, 2, 'session', '{builds,2,steps,0,prompt}', '{builds,2,steps,0,prompt}', 'patch', '7dce77eb8cd9ab3c68e0472cd431a375', null,
    $n$[["\nfrom reply import generate_reply\n\napp = Flask(__name__)\n", "\nfrom reply import generate_reply\nfrom sdt_ai import AIError\n\napp = Flask(__name__)\n"], ["MAX_HISTORY_TURNS = 6  # 3 back-and-forths of context - enough to feel continuous, bounded so cost can't grow forever\n\n\n@app.route(\"/whatsapp\", methods=[\"POST\"])\n", "MAX_HISTORY_TURNS = 6  # 3 back-and-forths of context - enough to feel continuous, bounded so cost can't grow forever\n\n# Sent when the AI can't answer (the free tier is busy, you've hit its rate\n# limit, or the internet is down), so the person still hears back instead\n# of getting silence.\nFALLBACK_REPLY = \"Sorry, I can't reply properly right now - give me a few minutes and I'll get back to you!\"\n\n\n@app.route(\"/whatsapp\", methods=[\"POST\"])\n"], ["\n    history = CONVERSATION_HISTORY.get(sender, [])\n    reply_text = generate_reply(incoming_message, history=history)\n\n    # Append this turn AFTER generating the reply (not before), so a\n", "\n    history = CONVERSATION_HISTORY.get(sender, [])\n    try:\n        reply_text = generate_reply(incoming_message, history=history)\n    except AIError as problem:\n        # Without this, Flask answers Twilio with a 500 error and the\n        # sender gets no reply at all. Print the real reason for you,\n        # send them the fallback, and leave history alone - this turn\n        # never really happened.\n        print(f\"AI error, sent the fallback reply instead: {problem}\")\n        return _twiml_response(FALLBACK_REPLY)\n\n    # Append this turn AFTER generating the reply (not before), so a\n"]]$n$, '4d4a8b412c3f5c094a451c61cc2e95a2'),
  (21, 2, 'session', '{builds,2,steps,1,prompt}', '{builds,2,steps,1,prompt}', 'patch', '6246ace20900bca03b2ea2ffdabb0aa3', null,
    $n$[["\n\nif __name__ == \"__main__\":\n    test_whatsapp_webhook_returns_valid_twiml()\n    test_empty_message_never_reaches_the_ai()\n", "\n\ndef test_ai_failure_still_sends_a_reply():\n    \"\"\"\n    When Gemini is busy or unreachable, ask_ai raises AIError. The webhook\n    must still answer Twilio with valid TwiML (the fallback message), not\n    crash with a 500 that leaves the sender with no reply at all.\n    \"\"\"\n\n    def _ai_is_down(*args, **kwargs):\n        raise app_module.AIError(\"Gemini is busy (test)\")\n\n    original_ask_ai = reply_module.ask_ai\n    reply_module.ask_ai = _ai_is_down\n    try:\n        client = app_module.app.test_client()\n        response = client.post(\"/whatsapp\", data={\"Body\": \"Hello?\", \"From\": \"whatsapp:+15550000000\"})\n        body = response.get_data(as_text=True)\n        assert response.status_code == 200\n        assert \"<Message>\" in body and \"get back to you\" in body\n        assert \"whatsapp:+15550000000\" not in app_module.CONVERSATION_HISTORY\n        print(\"\\nResponse when the AI is down:\")\n        print(body)\n        print(\"PASS: an AI failure still sends the fallback reply.\")\n    finally:\n        reply_module.ask_ai = original_ask_ai\n\n\nif __name__ == \"__main__\":\n    test_whatsapp_webhook_returns_valid_twiml()\n    test_empty_message_never_reaches_the_ai()\n    test_ai_failure_still_sends_a_reply()\n"]]$n$, 'b2bb1eb93f872bca199510f719d3dc2a'),
  (22, 2, 'session', '{builds,2,steps,1,verify}', '{builds,2,steps,1,verify}', 'str', '6bda7291ede98790849b069319d65ffd', null,
    $n$With app.py still running in another terminal, run `python test_app.py`. You should see three "PASS" lines: one confirming valid TwiML containing the expected reply, one confirming an empty message never reaches the AI, and one confirming the bot still sends a fallback reply when the AI is down.$n$, null),
  (23, 2, 'session', '{builds,3,steps,0,prompt}', '{builds,3,steps,0,prompt}', 'str', 'cb1ede75b240f3c651e54dd146990108', null,
    $n$Help me deploy this Flask WhatsApp bot to Railway. Walk me through:
1. Initializing a git repo and pushing this project to a new GitHub repo (give me the exact commands)
2. Connecting that repo to a new Railway project
3. Which environment variables I need to add in the Railway dashboard (GEMINI_API_KEY, and TWILIO_ACCOUNT_SID/TWILIO_AUTH_TOKEN if I'm using the Twilio SDK)
4. Making sure app.py listens on the PORT environment variable via os.environ.get("PORT", 3000) so Railway can route to it (it already does - just confirm)
5. Adding a Procfile or start command so Railway runs `python app.py`
6. Creating a requirements.txt listing flask, requests and python-dotenv, so Railway installs them

Give me a step-by-step checklist I can follow.$n$, null),
  (24, 2, 'troubleshooting', '{2,fix}', '{2,fix}', 'str', 'ecd5a825c2e11a4c417ea87f38b13907', null,
    $n$Your virtual environment is not active, or the install step was skipped. From the project folder, run the activate line from the first step (`source .venv/bin/activate`, or `.venv\Scripts\Activate.ps1` on Windows), then `python -m pip install flask requests python-dotenv` again.$n$, null),
  (25, 3, 'session', '{builds,1,steps,1,prompt}', '{builds,1,steps,1,prompt}', 'patch', 'faaf68c88f6cb6ed7d22d8a7643c95fd', null,
    $n$[["\n# Slack timestamps (\"ts\") are UNIX seconds as a string, e.g. \"1699999999.000100\".\nSECONDS_PER_DAY = 24 * 60 * 60\n\n\n", "\n# Slack timestamps (\"ts\") are UNIX seconds as a string, e.g. \"1699999999.000100\".\nSECONDS_PER_HOUR = 60 * 60\n\n\n"], ["    that's where the logic actually worth testing lives.\n    \"\"\"\n    oldest = str(time.time() - hours * SECONDS_PER_DAY)\n    messages = []\n    cursor = None\n", "    that's where the logic actually worth testing lives.\n    \"\"\"\n    oldest = str(time.time() - hours * SECONDS_PER_HOUR)\n    messages = []\n    cursor = None\n"]]$n$, '3d7a8b85ee24465f66c32b1961f0aeb9'),
  (26, 3, 'session', '{builds,1,steps,2,prompt}', '{builds,1,steps,2,prompt}', 'patch', '38cfd13f07821559afc672cca294c2f6', null,
    $n$[["\n\ndef build_prompt(channel_texts):\n    \"\"\"\n", "\n\ndef _keep_latest(channel_text, budget):\n    \"\"\"\n    Trims one channel's text to about `budget` characters by dropping its\n    OLDEST lines. Messages arrive oldest-first, so the newest ones - the\n    overnight messages most likely to need attention this morning - are\n    at the end, and they're the ones worth keeping. Cutting from the end\n    instead would throw away exactly what the briefing is for.\n    \"\"\"\n    if len(channel_text) <= budget:\n        return channel_text\n\n    header, _, body = channel_text.partition(\"\\n\")\n    marker = \"[...older messages trimmed]\"\n    room = budget - len(header) - len(marker) - 2\n    kept = []\n    for line in reversed(body.splitlines()):\n        if len(line) + 1 > room:\n            break\n        kept.append(line)\n        room -= len(line) + 1\n    if not kept:\n        # A single message longer than the whole budget - keep its end.\n        kept = [body[len(body) - max(room, 0):]]\n    kept.reverse()\n    return header + \"\\n\" + marker + \"\\n\" + \"\\n\".join(kept)\n\n\ndef build_prompt(channel_texts):\n    \"\"\"\n"], ["    slack_client.filter_and_format_messages() as \"--- #channel ---\\\\n...\".\n    \"\"\"\n    combined = \"\\n\\n\".join(channel_texts)[:MAX_CHARACTERS]\n\n    return f\"\"\"You are preparing a morning briefing for someone who was away from\n", "    slack_client.filter_and_format_messages() as \"--- #channel ---\\\\n...\".\n    \"\"\"\n    # Each channel gets an equal share of MAX_CHARACTERS, so one very loud\n    # channel can't push the others out of the briefing entirely.\n    budget = MAX_CHARACTERS // max(len(channel_texts), 1)\n    combined = \"\\n\\n\".join(_keep_latest(text, budget) for text in channel_texts)\n\n    return f\"\"\"You are preparing a morning briefing for someone who was away from\n"], ["    assert len(huge_prompt) < len(huge_input[0]) + 2000, \"MAX_CHARACTERS should have capped this\"\n\n    print(\"\\nAll summarizer.py self-tests passed.\")\n", "    assert len(huge_prompt) < len(huge_input[0]) + 2000, \"MAX_CHARACTERS should have capped this\"\n\n    # ...and what gets cut is the OLDEST chatter, never the newest, while a\n    # second, quieter channel still makes it into the prompt.\n    loud = \"--- #general ---\\n\" + \"\\n\".join(f\"U1: message {i}\" for i in range(2000))\n    quiet = \"--- #eng-team ---\\nU2: deploy is blocked, need a decision today\"\n    trimmed_prompt = build_prompt([loud, quiet])\n    assert \"U1: message 1999\" in trimmed_prompt, \"the newest message should survive trimming\"\n    assert \"U1: message 0\\n\" not in trimmed_prompt, \"the oldest messages should be the ones trimmed\"\n    assert \"deploy is blocked\" in trimmed_prompt, \"a quiet channel must not be crowded out\"\n\n    print(\"\\nAll summarizer.py self-tests passed.\")\n"]]$n$, '38b8b35ebc036ae0cf96cc388d28c2c2'),
  (27, 3, 'session', '{builds,1,steps,2,verify}', '{builds,1,steps,2,verify}', 'str', 'deee9db4163d081acb01285ecd8e526f', null,
    $n$Run `python summarizer.py`. It checks the parser against a well-formed reply, a malformed reply with no markers at all, and an oversized input that should get trimmed to MAX_CHARACTERS by dropping the oldest messages (never the newest, and never a whole quieter channel) - all without spending any Gemini credits. You should see "All summarizer.py self-tests passed." at the end.$n$, null),
  (28, 10, 'session', '{builds,3,steps,0,prompt}', '{builds,3,steps,0,prompt}', 'patch', '6d023c2bcf6d33091459e8d99cd1593c', null,
    $n$[["    current = {}\n    scrape_errors = []\n\n    for entry in TARGETS:\n", "    current = {}\n    scrape_errors = []\n    failed_targets = []\n\n    for entry in TARGETS:\n"], ["            # checking every other target, and just report this one.\n            scrape_errors.append(f\"{entry['target']}: {problem}\")\n\n    for problem in scrape_errors:\n        print(f\"Skipped a target: {problem}\")\n\n    changes = diff_snapshots(previous, current)\n", "            # checking every other target, and just report this one.\n            scrape_errors.append(f\"{entry['target']}: {problem}\")\n            failed_targets.append(entry[\"target\"])\n\n    for problem in scrape_errors:\n        print(f\"Skipped a target: {problem}\")\n\n    if not previous:\n        # Very first run: there's nothing to compare against yet, and\n        # diffing against an empty snapshot would report every target as\n        # a \"new product\". Just save today's scrape as the starting point.\n        save_snapshot(SNAPSHOT_FILE, current)\n        print(f\"First run: saved a snapshot of {len(current)} target(s) to compare against next time.\")\n        return\n\n    changes = diff_snapshots(previous, current)\n"], ["    # against the same stale snapshot forever, which is a subtler\n    # version of the \"alert every run\" bug in the troubleshooting notes.\n    save_snapshot(SNAPSHOT_FILE, current)\n\n", "    # against the same stale snapshot forever, which is a subtler\n    # version of the \"alert every run\" bug in the troubleshooting notes.\n    #\n    # A target that failed to scrape this time keeps its last known data\n    # in the file. Dropping it would make the next successful scrape look\n    # like a brand-new product, and a target that keeps failing would be\n    # reported missing once and then silently forgotten.\n    for target_name in failed_targets:\n        if target_name in previous:\n            current[target_name] = previous[target_name]\n    save_snapshot(SNAPSHOT_FILE, current)\n\n"], ["    # A schedule on your own laptop only fires while the laptop is on\n    # and awake -- it silently stops the moment it sleeps or shuts down.\n    # For real always-on monitoring, deploy this the same way as the\n    # WhatsApp/Gmail course guides (a free always-on host).", "    # A schedule on your own laptop only fires while the laptop is on\n    # and awake -- it silently stops the moment it sleeps or shuts down.\n    # For real always-on monitoring, deploy it to an always-on host such\n    # as Railway or Render (check their current plans - neither keeps a\n    # job running 24/7 for free)."]]$n$, 'c159496d4f930c15178d8e86db384f86'),
  (29, 10, 'session', '{builds,3,steps,0,verify}', '{builds,3,steps,0,verify}', 'str', 'be482d0170b13e5507e438b6a45c9803', null,
    $n$Run `python main.py`. The first run just saves a snapshot and prints "First run: saved a snapshot of ..." (there's nothing to compare against yet). Run it again and you should see "No changes detected." Temporarily change a price on one of your target pages, or hand-edit snapshot.json, and run it again - you should see the change listed plus Gemini's summary printed under "--- Alert ---".$n$, null),
  (30, 10, 'session', '{builds,3,steps,2,instruction}', '{builds,3,steps,2,instruction}', 'str', 'a008994a3ff403d78abf90e6772d3102', null,
    $n$Ask an AI assistant how to schedule main.py to run automatically instead of by hand - cron on Mac/Linux, Task Scheduler on Windows, or an always-on host such as Railway or Render if you want it running even while your laptop is off (check their current plans - neither keeps a job running 24/7 for free). A commented-out crontab line for every 6 hours is already at the bottom of main.py.$n$, null),
  (31, 11, 'session', '{builds,0,steps,2,prompt}', '{builds,0,steps,2,prompt}', 'patch', 'beb965d10825f820a1573174e841d19c', null,
    $n$[["            raise FileNotFoundError(\n                f\"Missing {CREDENTIALS_FILE}.\\n\"\n                \"Download it from Google Cloud Console (see README Build 2) \"\n                \"and put it in this same folder, then run this again.\"\n            )\n", "            raise FileNotFoundError(\n                f\"Missing {CREDENTIALS_FILE}.\\n\"\n                \"Download it from Google Cloud Console (Build 1 of the guide) \"\n                \"and put it in this same folder, then run this again.\"\n            )\n"], ["    an automated test.\n    \"\"\"\n    today_start = datetime.datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)\n    today_end = today_start + datetime.timedelta(days=1)\n\n    return service.events().list(\n        calendarId=calendar_id,\n        timeMin=today_start.isoformat() + \"Z\",\n        timeMax=today_end.isoformat() + \"Z\",\n        singleEvents=True,\n        orderBy=\"startTime\",\n", "    an automated test.\n    \"\"\"\n    # Midnight to midnight in YOUR timezone. astimezone() attaches your\n    # computer's UTC offset, so isoformat() writes e.g.\n    # \"2026-09-02T00:00:00+01:00\". Gluing a \"Z\" (UTC) onto a local time\n    # instead would shift the whole day by your UTC offset - pulling in\n    # yesterday's late events or dropping tonight's.\n    today_start = datetime.datetime.now().astimezone().replace(hour=0, minute=0, second=0, microsecond=0)\n    today_end = today_start + datetime.timedelta(days=1)\n\n    return service.events().list(\n        calendarId=calendar_id,\n        timeMin=today_start.isoformat(),\n        timeMax=today_end.isoformat(),\n        singleEvents=True,\n        orderBy=\"startTime\",\n"], ["    assert parse_events({}) == []\n\n    print(\"\\nAll checks passed.\")", "    assert parse_events({}) == []\n\n    # The day window sent to Google must carry your real UTC offset and\n    # start at your local midnight. A stand-in for the Calendar service\n    # records what fetch_todays_events() asks for, without any network.\n    class _FakeRequest:\n        def list(self, **kwargs):\n            self.kwargs = kwargs\n            return self\n\n        def execute(self):\n            return {\"items\": []}\n\n    class _FakeService:\n        request = _FakeRequest()\n\n        def events(self):\n            return self.request\n\n    fake_service = _FakeService()\n    fetch_todays_events(fake_service)\n    start = datetime.datetime.fromisoformat(fake_service.request.kwargs[\"timeMin\"])\n    assert start.utcoffset() == datetime.datetime.now().astimezone().utcoffset()\n    assert (start.hour, start.minute) == (0, 0)\n\n    print(\"\\nAll checks passed.\")"]]$n$, '8857af20b5e2647e50acf1f6751c478e'),
  (32, 11, 'session', '{builds,2,steps,0,prompt}', '{builds,2,steps,0,prompt}', 'patch', 'aff8e33f8adb67527cda9fc0c0aa33ed', null,
    $n$[["    try:\n        result = plan_day(events, tasks)\n    except AIError as problem:\n        # Written to be read - show it as-is, same convention as every\n        # other project in this course.\n        print(problem)\n        return\n", "    try:\n        result = plan_day(events, tasks)\n    except (AIError, ValueError) as problem:\n        # AIError: the AI couldn't be reached. ValueError: it answered, but\n        # not in the format plan_day() asked for. Both messages are written\n        # to be read - show them as-is, same convention as every other\n        # project in this course.\n        print(problem)\n        return\n"]]$n$, '0e337c5a71d8de4608d833d6db9b069f');

-- 2. Self-check, pre-flight guards, backup, apply, post-check.
do $$
declare e record; cur jsonb; par jsonb; n int; txt text; pr jsonb;
begin
  if (select md5(string_agg(h, '' order by h collate "C")) from (
        select md5(concat_ws(E'\x1f', ord::text, course_id::text, col, array_to_string(path, '.'),
                             array_to_string(final, '.'), kind, new_text, coalesce(new_md5, ''))) as h
          from content_edits) s) <> '4ab4cb2d7bd04526ed793b6467b2a1f7' then
    raise exception 'Section 1 is not the reviewed copy - nothing was changed.';
  end if;
  if to_regclass('public.course_content_backup_20260926_b1_fixes') is not null then
    raise exception 'public.course_content_backup_20260926_b1_fixes already exists - has this migration already run?';
  end if;
  create table public.course_content_backup_20260926_b1_fixes as
    select course_id, session, troubleshooting, resources, updated_at from public.course_content
     where course_id in (2, 3, 5, 6, 7, 8, 10, 11, 12);
  alter table public.course_content_backup_20260926_b1_fixes enable row level security;
  revoke all on public.course_content_backup_20260926_b1_fixes from anon, authenticated;

  for e in select * from content_edits order by ord loop
    n := array_length(e.path, 1);
    execute format('select %I #> $1, %I #> $2 from public.course_content where course_id = $3', e.col, e.col)
      into cur, par using e.path, e.path[1:n-1], e.course_id;
    if (e.kind in ('str', 'patch') and md5(cur #>> '{}') is distinct from e.old_md5)
       or (e.kind = 'json' and cur is distinct from e.old_json::jsonb)
       or (e.kind = 'add' and (cur is not null or jsonb_typeof(par) is distinct from 'object'))
       or (e.kind = 'insert' and (jsonb_typeof(par) is distinct from 'array'
            or jsonb_array_length(par) <> e.old_json::int
            or md5(coalesce(cur ->> 'instruction', cur #>> '{}')) is distinct from e.old_md5)) then
      raise exception 'edit % (course % %.%) does not match the audited value - nothing was changed',
        e.ord, e.course_id, e.col, array_to_string(e.path, '.');
    end if;
    if e.kind = 'patch' then
      -- replay the reviewed hunks; each must match exactly once, and the result must hash to new_md5
      txt := cur #>> '{}';
      for pr in select value from jsonb_array_elements(e.new_text::jsonb) loop
        if (length(txt) - length(replace(txt, pr ->> 0, ''))) / length(pr ->> 0) <> 1 then
          raise exception 'edit % (course %): a patch hunk does not match exactly once - nothing was changed', e.ord, e.course_id;
        end if;
        txt := replace(txt, pr ->> 0, pr ->> 1);
      end loop;
      if md5(txt) <> e.new_md5 then
        raise exception 'edit % (course %): patched text is not the reviewed result - nothing was changed', e.ord, e.course_id;
      end if;
      execute format('update public.course_content set %I = jsonb_set(%I, $1, $2), updated_at = now() where course_id = $3', e.col, e.col)
        using e.path, to_jsonb(txt), e.course_id;
    elsif e.kind = 'insert' then
      execute format('update public.course_content set %I = jsonb_insert(%I, $1, $2), updated_at = now() where course_id = $3', e.col, e.col)
        using e.path, e.new_text::jsonb, e.course_id;
    else
      execute format('update public.course_content set %I = jsonb_set(%I, $1, $2), updated_at = now() where course_id = $3', e.col, e.col)
        using e.path, case when e.kind = 'str' then to_jsonb(e.new_text) else e.new_text::jsonb end, e.course_id;
    end if;
  end loop;

  for e in select * from content_edits order by ord loop
    execute format('select %I #> $1 from public.course_content where course_id = $2', e.col)
      into cur using e.final, e.course_id;
    if (e.kind = 'patch' and md5(cur #>> '{}') is distinct from e.new_md5)
       or (e.kind <> 'patch' and cur is distinct from (case when e.kind = 'str' then to_jsonb(e.new_text) else e.new_text::jsonb end)) then
      raise exception 'post-check: edit % (course %) did not land - rolling back', e.ord, e.course_id;
    end if;
  end loop;
  if exists (select 1 from public.course_content where updated_at = now() and course_id not in (2, 3, 5, 6, 7, 8, 10, 11, 12)) then
    raise exception 'post-check: an untouched row changed - rolling back';
  end if;
end $$;
