import { useParams, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { usePageSeo } from '../hooks/usePageSeo';

const PAGES = {
  terms: {
    title: 'Terms of Service',
    updated: 'July 2026',
    sections: [
      {
        heading: '1. Acceptance of Terms',
        body: 'By accessing or using Social Dev Technologies ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Platform.',
      },
      {
        heading: '2. Description of Service',
        body: 'Social Dev Technologies provides self-paced AI agent learning sessions and live instructor-led cohorts. Content is educational in nature and designed to teach practical AI and digital skills.',
      },
      {
        heading: '3. User Accounts',
        body: 'You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials. You may not share your account with others.',
      },
      {
        heading: '4. Payments & Subscriptions',
        body: 'Pro subscriptions are billed monthly and can be cancelled at any time. Live class enrollments are one-time payments and are non-refundable after the cohort begins. BYU Pathway student discounts require a valid @byupathway.edu email address.',
      },
      {
        heading: '5. Intellectual Property',
        body: 'All course content, prompts, session guides, and materials are the property of Social Dev Technologies. You may use the knowledge gained for personal and professional projects but may not resell or redistribute our content.',
      },
      {
        heading: '6. Acceptable Use',
        body: 'You agree not to use the Platform for any unlawful purpose, to harass other users, or to interfere with the Platform\'s operation. We reserve the right to suspend accounts that violate these terms.',
      },
      {
        heading: '7. Disclaimer of Warranties',
        body: 'The Platform is provided "as is" without warranties of any kind. We do not guarantee specific career outcomes, income increases, or employment from completing our courses.',
      },
      {
        heading: '8. Contact',
        body: 'For questions about these terms, contact us at support@socialdevtechnologies.com.',
      },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    updated: 'July 2026',
    sections: [
      {
        heading: '1. Information We Collect',
        body: 'We collect information you provide (name, email address, payment details) and information generated by your use of the Platform (progress data, completed sessions, XP, login timestamps).',
      },
      {
        heading: '2. How We Use Your Information',
        body: 'We use your information to provide and improve the Platform, process payments, send account notifications, and inform admins of new registrations. We do not sell your personal data to third parties.',
      },
      {
        heading: '3. BYU Pathway Email Addresses',
        body: 'If you sign up with a @byupathway.edu email, we automatically flag your account for the student discount program. This flag is visible to Platform administrators only.',
      },
      {
        heading: '4. Data Storage',
        body: 'Your data is stored securely using Supabase, which uses industry-standard encryption. Payment processing is handled by Paystack — we do not store card details.',
      },
      {
        heading: '5. Cookies',
        body: 'We use essential cookies for authentication (keeping you logged in). We do not use advertising or tracking cookies.',
      },
      {
        heading: '6. Your Rights',
        body: 'You may request deletion of your account and data at any time by emailing support@socialdevtechnologies.com. We will process requests within 30 days.',
      },
      {
        heading: '7. Third-Party Services',
        body: 'The Platform uses Supabase (authentication & database), Paystack (payment processing), and Resend (transactional email). Each has its own privacy policy.',
      },
      {
        heading: '8. Contact',
        body: 'For privacy concerns, contact us at support@socialdevtechnologies.com.',
      },
    ],
  },
};

export default function Legal() {
  const { page } = useParams();
  const content = PAGES[page];

  // Called unconditionally (rules-of-hooks) — falls back to a generic title
  // for an unrecognised :page rather than skipping the hook.
  usePageSeo({
    title: content ? `${content.title} | Social Dev Technologies` : 'Social Dev Technologies',
    description: content ? `${content.title} for Social Dev Technologies — last updated ${content.updated}.` : undefined,
    canonicalPath: content ? `/legal/${page}` : undefined,
  });

  if (!content) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <p className="text-ink text-xl font-bold mb-4">Page not found</p>
          <Link to="/" className="text-brand hover:underline">Back to home</Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}>
          <div className="flex gap-4 mb-8 text-sm">
            <Link to="/legal/terms" className={`font-semibold transition-colors ${page === 'terms' ? 'text-ink border-b-2 border-brand pb-1' : 'text-body hover:text-ink'}`}>Terms of Service</Link>
            <Link to="/legal/privacy" className={`font-semibold transition-colors ${page === 'privacy' ? 'text-ink border-b-2 border-brand pb-1' : 'text-body hover:text-ink'}`}>Privacy Policy</Link>
          </div>

          <h1 className="font-display text-3xl sm:text-4xl font-extrabold text-ink mb-2">{content.title}</h1>
          <p className="text-gray-400 text-sm mb-10">Last updated: {content.updated}</p>

          <div className="space-y-8">
            {content.sections.map((s) => (
              <div key={s.heading}>
                <h2 className="text-base font-bold text-ink mb-2">{s.heading}</h2>
                <p className="text-body text-sm leading-relaxed">{s.body}</p>
              </div>
            ))}
          </div>

          <div className="mt-12 pt-8 border-t border-border-soft text-center">
            <Link to="/" className="text-sm text-brand hover:underline">← Back to Social Dev Technologies</Link>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
