// Splices the locally-prerendered homepage snapshot (public/prerendered-
// home.html, regenerated by `npm run prerender`) into the real dist/
// index.html that THIS build just produced. Pure string manipulation, no
// browser involved — safe to run as part of Vercel's own build command,
// unlike the actual Puppeteer-based prerender step (see scripts/
// prerender.mjs's header comment for why that has to stay local-only).
//
// Why this is needed at all: Vercel's routing checks for a literal static
// file at the request path BEFORE applying any vercel.json rewrite. Since
// vite build always produces a real dist/index.html (Vite's entry
// template, output as the empty CSR shell), a `"/"` → `/prerendered-
// home.html` rewrite never gets a chance to fire — the literal file always
// wins. So instead of rewriting, we make dist/index.html itself already
// contain the real content.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const snapshotPath = path.join(root, 'public', 'prerendered-home.html');
const distIndexPath = path.join(root, 'dist', 'index.html');

async function main() {
  const [snapshot, distIndex] = await Promise.all([
    readFile(snapshotPath, 'utf-8').catch(() => null),
    readFile(distIndexPath, 'utf-8'),
  ]);

  if (!snapshot) {
    console.warn('[inject-home] public/prerendered-home.html not found — leaving dist/index.html as the plain CSR shell.');
    return;
  }

  const bodyMatch = snapshot.match(/<body[^>]*>([\s\S]*)<\/body>/i);
  if (!bodyMatch) {
    console.warn('[inject-home] Could not find <body> in the snapshot — leaving dist/index.html untouched.');
    return;
  }

  const injected = distIndex.replace(
    /<body([^>]*)>[\s\S]*<\/body>/i,
    `<body$1>${bodyMatch[1]}</body>`,
  );

  await writeFile(distIndexPath, injected, 'utf-8');
  console.log('[inject-home] ✓ dist/index.html now contains the prerendered homepage.');
}

main();
